name: README publish
on: 
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/**"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.DSD_ACCOUNT_ID}}:role/TrustPolicy-OpsEngineering-Terraform
          role-session-name: GitHubActions
          aws-region: eu-west-2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r scripts/requirements.txt
      - run: python scripts/readme-publisher.py
      - uses: stefanzweifel/git-auto-commit-action@v5
      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: 'Failed GitHub Action Run'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}