name: Remove Gandi CNAME records

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 1-12 *"

jobs:
  remove-Gandi-cname-records:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python scripts/remove-cnames.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: remove Gandi cname records
          title: Clean up Gandi cnames from terraform files
          body: These Gandi cname records have exceed the four week grace period
          branch: automation-remove-gandi-cnames
