name: Terraform plan
on: [workflow_dispatch, pull_request]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'terraform/**'

      - if: steps.changes.outputs.src == 'true'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.2

      - if: steps.changes.outputs.src == 'true'
        name: terraform plan
        run: |
          cd terraform
          terraform init
          terraform plan

      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: 'Failed GitHub Action Run'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}