name: Terraform plan
on: 
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-plan.yml"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{secrets.DSD_ACCOUNT_ID}}:role/TrustPolicy-OpsEngineering-Terraform
          role-session-name: GitHubActions
          aws-region: eu-west-2
      - name: terraform plan
        run: |
          cd terraform
          terraform init
          terraform plan --parallelism=50
      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: 'Failed GitHub Action Run'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
